
package ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotTicketFoundException", targetNamespace = "http://ws/")
public class NotTicketFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotTicketFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotTicketFoundException_Exception(String message, NotTicketFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotTicketFoundException_Exception(String message, NotTicketFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.NotTicketFoundException
     */
    public NotTicketFoundException getFaultInfo() {
        return faultInfo;
    }

}
