
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketServiceImpService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8085/TicketService/TicketService?wsdl")
public class TicketServiceImpService
    extends Service
{

    private final static URL TICKETSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TICKETSERVICEIMPSERVICE_EXCEPTION;
    private final static QName TICKETSERVICEIMPSERVICE_QNAME = new QName("http://ws/", "TicketServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/TicketService/TicketService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETSERVICEIMPSERVICE_WSDL_LOCATION = url;
        TICKETSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public TicketServiceImpService() {
        super(__getWsdlLocation(), TICKETSERVICEIMPSERVICE_QNAME);
    }

    public TicketServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETSERVICEIMPSERVICE_QNAME, features);
    }

    public TicketServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, TICKETSERVICEIMPSERVICE_QNAME);
    }

    public TicketServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETSERVICEIMPSERVICE_QNAME, features);
    }

    public TicketServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketServiceImp
     */
    @WebEndpoint(name = "TicketServiceImpPort")
    public TicketServiceImp getTicketServiceImpPort() {
        return super.getPort(new QName("http://ws/", "TicketServiceImpPort"), TicketServiceImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketServiceImp
     */
    @WebEndpoint(name = "TicketServiceImpPort")
    public TicketServiceImp getTicketServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "TicketServiceImpPort"), TicketServiceImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw TICKETSERVICEIMPSERVICE_EXCEPTION;
        }
        return TICKETSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
