
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketProcessing", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketProcessing {


    /**
     * 
     * @param dataTransfer
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveTicket", targetNamespace = "http://ws/", className = "ws.ReserveTicket")
    @ResponseWrapper(localName = "reserveTicketResponse", targetNamespace = "http://ws/", className = "ws.ReserveTicketResponse")
    @Action(input = "http://ws/TicketProcessing/reserveTicketRequest", output = "http://ws/TicketProcessing/reserveTicketResponse")
    public int reserveTicket(
        @WebParam(name = "dataTransfer", targetNamespace = "")
        DataTransfer dataTransfer);

    /**
     * 
     * @param ticketNum
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTicket", targetNamespace = "http://ws/", className = "ws.ReturnTicket")
    @ResponseWrapper(localName = "returnTicketResponse", targetNamespace = "http://ws/", className = "ws.ReturnTicketResponse")
    @Action(input = "http://ws/TicketProcessing/returnTicketRequest", output = "http://ws/TicketProcessing/returnTicketResponse")
    public boolean returnTicket(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum);

    /**
     * 
     * @param ticketNum
     * @return
     *     returns ws.Ticket
     * @throws IsPaidException_Exception
     * @throws NotTicketFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payTicket", targetNamespace = "http://ws/", className = "ws.PayTicket")
    @ResponseWrapper(localName = "payTicketResponse", targetNamespace = "http://ws/", className = "ws.PayTicketResponse")
    @Action(input = "http://ws/TicketProcessing/payTicketRequest", output = "http://ws/TicketProcessing/payTicketResponse", fault = {
        @FaultAction(className = IsPaidException_Exception.class, value = "http://ws/TicketProcessing/payTicket/Fault/IsPaidException"),
        @FaultAction(className = NotTicketFoundException_Exception.class, value = "http://ws/TicketProcessing/payTicket/Fault/NotTicketFoundException")
    })
    public Ticket payTicket(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum)
        throws IsPaidException_Exception, NotTicketFoundException_Exception
    ;

    /**
     * 
     * @param ticketNum
     * @return
     *     returns ws.Ticket
     * @throws NotTicketFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketUsingNum", targetNamespace = "http://ws/", className = "ws.GetTicketUsingNum")
    @ResponseWrapper(localName = "getTicketUsingNumResponse", targetNamespace = "http://ws/", className = "ws.GetTicketUsingNumResponse")
    @Action(input = "http://ws/TicketProcessing/getTicketUsingNumRequest", output = "http://ws/TicketProcessing/getTicketUsingNumResponse", fault = {
        @FaultAction(className = NotTicketFoundException_Exception.class, value = "http://ws/TicketProcessing/getTicketUsingNum/Fault/NotTicketFoundException")
    })
    public Ticket getTicketUsingNum(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum)
        throws NotTicketFoundException_Exception
    ;

}
