
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketServiceImp", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketServiceImp {


    /**
     * 
     * @param ticketNum
     * @return
     *     returns ws.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketUsingNum", targetNamespace = "http://ws/", className = "ws.GetTicketUsingNum")
    @ResponseWrapper(localName = "getTicketUsingNumResponse", targetNamespace = "http://ws/", className = "ws.GetTicketUsingNumResponse")
    @Action(input = "http://ws/TicketServiceImp/getTicketUsingNumRequest", output = "http://ws/TicketServiceImp/getTicketUsingNumResponse")
    public Ticket getTicketUsingNum(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum);

    /**
     * 
     * @param lastName
     * @param departCity
     * @param name
     * @param patronymicName
     * @param departDate
     * @param arrivalCity
     * @param birthDate
     * @param arrivalDate
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveTicket", targetNamespace = "http://ws/", className = "ws.ReserveTicket")
    @ResponseWrapper(localName = "reserveTicketResponse", targetNamespace = "http://ws/", className = "ws.ReserveTicketResponse")
    @Action(input = "http://ws/TicketServiceImp/reserveTicketRequest", output = "http://ws/TicketServiceImp/reserveTicketResponse")
    public int reserveTicket(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "patronymicName", targetNamespace = "")
        String patronymicName,
        @WebParam(name = "departCity", targetNamespace = "")
        String departCity,
        @WebParam(name = "arrivalCity", targetNamespace = "")
        String arrivalCity,
        @WebParam(name = "departDate", targetNamespace = "")
        XMLGregorianCalendar departDate,
        @WebParam(name = "arrivalDate", targetNamespace = "")
        XMLGregorianCalendar arrivalDate,
        @WebParam(name = "birthDate", targetNamespace = "")
        XMLGregorianCalendar birthDate);

    /**
     * 
     * @param ticketNum
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTicket", targetNamespace = "http://ws/", className = "ws.ReturnTicket")
    @ResponseWrapper(localName = "returnTicketResponse", targetNamespace = "http://ws/", className = "ws.ReturnTicketResponse")
    @Action(input = "http://ws/TicketServiceImp/returnTicketRequest", output = "http://ws/TicketServiceImp/returnTicketResponse")
    public boolean returnTicket(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum);

    /**
     * 
     * @param ticketNum
     * @return
     *     returns ws.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payTicket", targetNamespace = "http://ws/", className = "ws.PayTicket")
    @ResponseWrapper(localName = "payTicketResponse", targetNamespace = "http://ws/", className = "ws.PayTicketResponse")
    @Action(input = "http://ws/TicketServiceImp/payTicketRequest", output = "http://ws/TicketServiceImp/payTicketResponse")
    public Ticket payTicket(
        @WebParam(name = "ticketNum", targetNamespace = "")
        int ticketNum);

}
