
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketProcessingService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8086/TicketService/tickets?wsdl")
public class TicketProcessingService
    extends Service
{

    private final static URL TICKETPROCESSINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException TICKETPROCESSINGSERVICE_EXCEPTION;
    private final static QName TICKETPROCESSINGSERVICE_QNAME = new QName("http://ws/", "TicketProcessingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/TicketService/tickets?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETPROCESSINGSERVICE_WSDL_LOCATION = url;
        TICKETPROCESSINGSERVICE_EXCEPTION = e;
    }

    public TicketProcessingService() {
        super(__getWsdlLocation(), TICKETPROCESSINGSERVICE_QNAME);
    }

    public TicketProcessingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETPROCESSINGSERVICE_QNAME, features);
    }

    public TicketProcessingService(URL wsdlLocation) {
        super(wsdlLocation, TICKETPROCESSINGSERVICE_QNAME);
    }

    public TicketProcessingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETPROCESSINGSERVICE_QNAME, features);
    }

    public TicketProcessingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketProcessingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketProcessing
     */
    @WebEndpoint(name = "TicketProcessingPort")
    public TicketProcessing getTicketProcessingPort() {
        return super.getPort(new QName("http://ws/", "TicketProcessingPort"), TicketProcessing.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketProcessing
     */
    @WebEndpoint(name = "TicketProcessingPort")
    public TicketProcessing getTicketProcessingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "TicketProcessingPort"), TicketProcessing.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETPROCESSINGSERVICE_EXCEPTION!= null) {
            throw TICKETPROCESSINGSERVICE_EXCEPTION;
        }
        return TICKETPROCESSINGSERVICE_WSDL_LOCATION;
    }

}
